language: go
sudo: true

services:
  - docker

install:
  - sudo apt-get install build-essential
  - make docker
  - make run

script:
  - make func-test
  - ./tests/tech-db-forum fill --wait=30 --thread=8

after_script:
  - make stop

